"""initial schema

Revision ID: 5ad13eeeeafb
Revises: 
Create Date: 2026-06-19 08:25:31.504678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ad13eeeeafb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('techniques',
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('technique_name', sa.String(length=100), nullable=True),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('technique_id')
    )
    op.create_index(op.f('ix_techniques_tactic'), 'techniques', ['tactic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('wazuh_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=100), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('technique_id', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('full_log', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wazuh_alerts_alert_id'), 'wazuh_alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_wazuh_alerts_rule_id'), 'wazuh_alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_wazuh_alerts_timestamp'), 'wazuh_alerts', ['timestamp'], unique=False)
    op.create_table('attacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=True),
    sa.Column('attack_name', sa.String(length=100), nullable=True),
    sa.Column('target_machine', sa.String(length=100), nullable=True),
    sa.Column('execution_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.technique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attacks_execution_time'), 'attacks', ['execution_time'], unique=False)
    op.create_index(op.f('ix_attacks_technique_id'), 'attacks', ['technique_id'], unique=False)
    op.create_index('ix_attacks_technique_time', 'attacks', ['technique_id', 'execution_time'], unique=False)
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=True),
    sa.Column('technique_name', sa.String(length=100), nullable=True),
    sa.Column('tactic', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=True),
    sa.Column('execution_log', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.technique_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulations_technique_id'), 'simulations', ['technique_id'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attack_id', sa.Integer(), nullable=True),
    sa.Column('wazuh_alert_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('detected', sa.Boolean(), nullable=True),
    sa.Column('latency_seconds', sa.Integer(), nullable=True),
    sa.Column('detection_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wazuh_alert_id'], ['wazuh_alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_attack_id'), 'detections', ['attack_id'], unique=False)
    op.create_index(op.f('ix_detections_detected'), 'detections', ['detected'], unique=False)
    op.create_index(op.f('ix_detections_detection_time'), 'detections', ['detection_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_detection_time'), table_name='detections')
    op.drop_index(op.f('ix_detections_detected'), table_name='detections')
    op.drop_index(op.f('ix_detections_attack_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_simulations_technique_id'), table_name='simulations')
    op.drop_table('simulations')
    op.drop_index('ix_attacks_technique_time', table_name='attacks')
    op.drop_index(op.f('ix_attacks_technique_id'), table_name='attacks')
    op.drop_index(op.f('ix_attacks_execution_time'), table_name='attacks')
    op.drop_table('attacks')
    op.drop_index(op.f('ix_wazuh_alerts_timestamp'), table_name='wazuh_alerts')
    op.drop_index(op.f('ix_wazuh_alerts_rule_id'), table_name='wazuh_alerts')
    op.drop_index(op.f('ix_wazuh_alerts_alert_id'), table_name='wazuh_alerts')
    op.drop_table('wazuh_alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_techniques_tactic'), table_name='techniques')
    op.drop_table('techniques')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
